### PR TITLE
DROPSEC-8519: Correctly parse the .env files

### PR DESCRIPTION
**Pull request by claudiu-cristea**

### CODE REVIEW

**Comment by joaocsilva** [comment]
Hi @claudiu-cristea ,
Please check the PR #744 and let me know if it works for you.
Best regards,
João Silva

**Comment by claudiu-cristea** [comment]
@joaocsilva that PR patch doesn't apply against Toolkit 10.8.1

**Comment by joaocsilva** [comment]
Hi @claudiu-cristea ,
The patch fail to apply because it contains changes to files that are not present in the distribution package.

**Comment by joaocsilva** [comment]
Hi @claudiu-cristea ,
Closing, issue was solved in #744 
And will be released on 10.9.0

**Pull request closed without merging**
